apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-first-deposit
  namespace: devops
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      backoffLimit: 3
      parallelism: 1
      suspend: false
      template:
        spec:
          activeDeadlineSeconds: 30
          containers:
          - env:
            - name: CONFIGPATH
              value: /config/config
            image: pgtgs/daily-first-deposit:latest
            imagePullPolicy: Always
            name: daily-first-deposit
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /config
              name: tgs-config
          - env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch-master.observability
            - name: ELASTICSEARCH_PORT
              value: "80"
            image: fluent/fluent-bit:latest
            imagePullPolicy: Always
            name: fluent-bit-sidecar
            resources: {}
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /fluent-bit/etc
              name: fluent-bit-config
            - mountPath: /var/log
              name: varlog
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: dockerhub
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: tgs-config
            name: tgs-config
          - configMap:
              defaultMode: 420
              name: google-json
            name: google-json
          - configMap:
              defaultMode: 420
              name: fluent-bit-config
            name: fluent-bit-config
          - hostPath:
              path: /var/log
              type: Directory
            name: varlog
      ttlSecondsAfterFinished: 600
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

