apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush        1
      Daemon       Off
      Log_Level    info
      Parsers_File parsers.conf

    [INPUT]
      Name             tail
      Path             /var/log/containers/expired-domains*_devops*.log
      Parser           docker, cri
      multiline.parser docker, cri
      Tag              devops.*
      Mem_Buf_Limit    5MB
      Refresh_Interval 5
      Skip_Long_Lines  On

    [OUTPUT]
      Name            es
      Match           devops.*
      Host            ${ELASTICSEARCH_HOST}
      Port            ${ELASTICSEARCH_PORT}
      Logstash_Format On
      Retry_Limit     False