apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace : devops
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log  # Adjust the pattern to match your log files
      pos_file /var/log/containerd/fluentd.pos  # Tracks the position of log file reading
      tag devops.*
    </source>

    <filter **>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type json
      </parse>
    </filter>

    <match **>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}" # Use environment variable or directly specify the host
      port "#{ENV['ELASTICSEARCH_PORT']}" # Use environment variable or directly specify the port
      logstash_format true
      include_tag_key true
      tag_key @log_name
      flush_interval 1s # Adjust based on your needs
    </match>