apiVersion: batch/v1
kind: CronJob
metadata:
  name: expired-domains
  namespace: devops
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 3
      parallelism: 1
      suspend: false
      template:
        spec:
          activeDeadlineSeconds: 3600
          containers:
          - image: pgtgs/expired_domain:latest
            imagePullPolicy: Always
            name: expired-domain
            env:
            - name: CONFIGPATH
              value: /config/config
            resources: {}
            volumeMounts:
            - mountPath: /config
              name: tgs-config
            - mountPath: /data
              name: google-json
          - name: fluentd-sidecar
            image: fluent/fluentd:latest # Use an appropriate Fluentd image
            env:
              - name: ELASTICSEARCH_HOST
                value: "elasticsearch-master.observability" # Change to your Elasticsearch service hostname
              - name: ELASTICSEARCH_PORT
                value: "80" # Default Elasticsearch port
            volumeMounts:
              - name: fluentd-config-volume
                mountPath: /fluentd/etc
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: dockerhub
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: tgs-config
            name: tgs-config
          - configMap:
              defaultMode: 420
              name: google-json
            name: google-json
          - name: fluentd-config-volume
            configMap:
              name: fluentd-config
      ttlSecondsAfterFinished: 86400
  schedule: 14 9 * * *
  successfulJobsHistoryLimit: 3
  suspend: false