apiVersion: batch/v1
kind: CronJob
metadata:
  name: expired-domains
  namespace: devops
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      suspend: false
      ttlSecondsAfterFinished: 86400
      activeDeadlineSeconds: 600
      backoffLimit: 3
      template:
        spec:
          activeDeadlineSeconds: 3600
          containers:
          - name: expired-domain
            image: pgtgs/expired_domain:latest
            command: ["./main"]
            env:
            - name: CONFIGPATH
              value: /config/config
            volumeMounts:
            - name: tgs-config
              mountPath: /config/config
            - name: google-json
              mountPath: /config/google.json
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: dockerhub
          volumes:
          - name: tgs-config
            configMap:
              name: tgs-config
          - name: google-json
            configMap:
              name: google-json