apiVersion: batch/v1
kind: CronJob
metadata:
  name: expired-domains
  namespace: devops
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 3
      parallelism: 1
      suspend: false
      template:
        spec:
          activeDeadlineSeconds: 3600
          containers:
          - env:
            - name: CONFIGPATH
              value: /config/config
            image: pgtgs/expired_domain:latest
            imagePullPolicy: Always
            name: expired-domain
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /config
              name: tgs-config
            - mountPath: /data
              name: google-json
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: dockerhub
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: tgs-config
            name: tgs-config
          - configMap:
              defaultMode: 420
              name: google-json
            name: google-json
      ttlSecondsAfterFinished: 86400
  schedule: 14 9 * * *
  successfulJobsHistoryLimit: 3
  suspend: false