apiVersion: batch/v1
kind: CronJob
metadata:
  name: expired-domains
  namespace: devops
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      suspend: false
      parallelism: 1
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          activeDeadlineSeconds: 3600
          containers:
          - name: expired_domain
            image: pgtgs/expired_domain:latest
            command: ["./main"]
            env:
            - name: CONFIGPATH
              value: /config/config
            volumeMounts:
            - name: tgs-config
              mountPath: /config
            - name: google-json
              mountPath: /config    
          restartPolicy: OnFailure
        volumes:
        - name: tgs-config
          configMap:
            name: tgs-config
            items:
            - key: config
              path: config
        - name: google-json
          configMap:
            name: google-json
            items:
            - key: googe-json
              path: config
