kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: golang:1.21.1
  commands:
  - ls -al
  - pwd
  - ll
  - go mod download
  - go build ./...

- name: test
  image: golang:1.16
  commands:
  - go test ./...

- name: deploy
  image: plugins/docker
  settings:
    repo: your_docker_repo
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: publish
  image: plugins/docker
  settings:
    registry: your_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: your_image_name
    tags:
      - $(date +%Y%m%d%H%M%S)
trigger:
  branch: 
  - main
  event:
  - push