kind: pipeline
type: kubernetes
name: default

clone:
  retries: 5
  
steps:
- name: build-and-test
  image: golang:1.21.1
  commands:
  - ls -al
  - pwd
  - hostname
  - go mod download
  - go build ./...
  - go test ./...
  - go build -o main ./cmd/expired_domain

- name: docker-build
  image: plugins/docker
  privileged: true
  settings:
    debug: true
    registry: registry.hub.docker.com
    repo: pgtgs/expired_domain
    tags: latest
    dockerfile: dockerfiles/Dockerfile.expired_domain
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    script:
    - docker login --username ${docker_username} --password ${docker_password}

trigger:
  branch: 
  - main
#   event:
#   - push
