kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: golang:1.21.1
  commands:
  - ls -al
  - pwd
  - hostname
  - go mod download
  - go build ./...

- name: test
  image: golang:1.21.1
  commands:
  - go test ./...

- name: docker-build
  image: plugins/docker
  privileged: true
  settings:
    debug: true
    registry: registry.hub.docker.com
    repo: pgtgs/expired_domain
    dockerfile: dockerfiles/Dockerfile.expired_domain
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  # volumes:
  #   - name: dockersock
  #     path: /var/run/docker.sock

- name: deploy
  image: plugins/docker
  settings:
    repo: your_docker_repo
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: publish
  image: plugins/docker
  settings:
    registry: your_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: your_image_name
    tags:
      - $(date +%Y%m%d%H%M%S)

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock

trigger:
  branch: 
  - main
#   event:
#   - push
