// Code generated by MockGen. DO NOT EDIT.
// Source: create_expired_domain.go
//
// Generated by this command:
//
//	mockgen -destination create_expired_domain_mock.go -source create_expired_domain.go -package googlesheet
//

// Package googlesheet is a generated GoMock package.
package googlesheet

import (
	postgresql "tgs-automation/pkg/postgresql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	sheets "google.golang.org/api/sheets/v4"
)

// MockGoogleSheetServiceInterface is a mock of GoogleSheetServiceInterface interface.
type MockGoogleSheetServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleSheetServiceInterfaceMockRecorder
}

// MockGoogleSheetServiceInterfaceMockRecorder is the mock recorder for MockGoogleSheetServiceInterface.
type MockGoogleSheetServiceInterfaceMockRecorder struct {
	mock *MockGoogleSheetServiceInterface
}

// NewMockGoogleSheetServiceInterface creates a new mock instance.
func NewMockGoogleSheetServiceInterface(ctrl *gomock.Controller) *MockGoogleSheetServiceInterface {
	mock := &MockGoogleSheetServiceInterface{ctrl: ctrl}
	mock.recorder = &MockGoogleSheetServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleSheetServiceInterface) EXPECT() *MockGoogleSheetServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateSheet mocks base method.
func (m *MockGoogleSheetServiceInterface) CreateSheet(sheetsService *sheets.Service, spreadsheetId, sheetName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSheet", sheetsService, spreadsheetId, sheetName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSheet indicates an expected call of CreateSheet.
func (mr *MockGoogleSheetServiceInterfaceMockRecorder) CreateSheet(sheetsService, spreadsheetId, sheetName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSheet", reflect.TypeOf((*MockGoogleSheetServiceInterface)(nil).CreateSheet), sheetsService, spreadsheetId, sheetName)
}

// CreateSheetsService mocks base method.
func (m *MockGoogleSheetServiceInterface) CreateSheetsService(key string) (*sheets.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSheetsService", key)
	ret0, _ := ret[0].(*sheets.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSheetsService indicates an expected call of CreateSheetsService.
func (mr *MockGoogleSheetServiceInterfaceMockRecorder) CreateSheetsService(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSheetsService", reflect.TypeOf((*MockGoogleSheetServiceInterface)(nil).CreateSheetsService), key)
}

// WriteData mocks base method.
func (m *MockGoogleSheetServiceInterface) WriteData(sheetService *sheets.Service, spreadsheetId string, domains []postgresql.DomainForExcel, writeRangeFunc func() string, valueRangeFunc func([]postgresql.DomainForExcel) *sheets.ValueRange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteData", sheetService, spreadsheetId, domains, writeRangeFunc, valueRangeFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteData indicates an expected call of WriteData.
func (mr *MockGoogleSheetServiceInterfaceMockRecorder) WriteData(sheetService, spreadsheetId, domains, writeRangeFunc, valueRangeFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteData", reflect.TypeOf((*MockGoogleSheetServiceInterface)(nil).WriteData), sheetService, spreadsheetId, domains, writeRangeFunc, valueRangeFunc)
}
