// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cdnetwork/internal/util"
)

// Injectors from wire.go:

func InitExpiredDomainsService(cfg util.TgsConfig) (*ExpiredDomainsService, error) {
	expiredDomainsService := newExpiredDomainsService(cfg)
	return expiredDomainsService, nil
}
